### ISSUE TITLE
레파지토리 세팅

### ISSUE THREAD

**Issue by rootachieve** [JNU-econovation/jnu-wiki-aos-v2#1]
## Description
프로젝트 생성과 기본적인 템플릿 설정과 같은 문서화 작업을 합니다.

## ToDo
- [x] git ignore 설정
- [x] android 프로젝트 생성
- [x] 이슈 템플릿 설정
- [x] pr 템플릿 설정
- [x] 브랜치 룰 적용

## ETC
초기 세팅 단계이기에 PR을 통한 반영이 아니라 다이렉트 커밋으로 진행합니다.
이후의 작업은 기능별 브랜치를 파고 develop에 pr을 날리는 방식으로 이루어집니다.
