### ISSUE TITLE
로그인 스크린

### ISSUE THREAD

**Issue by rootachieve** [JNU-econovation/jnu-wiki-aos-v2#2]
## Description
Sign 액티비티의 생성 및 로그인 화면을 구현합니다.

## Todo
- [x] sign activity 생성
- [x] login screen 작성
- [ ] login state 생성
- [ ] login viewmodel 생성 및 state 변경 함수 구현

## ETC
예외 처리에 대한 로직, 서버와의 연결은 추후 기능으로 빼서 개발합니다.
