### ISSUE TITLE
회원가입 스크린

### ISSUE THREAD

**Issue by rootachieve** [JNU-econovation/jnu-wiki-aos-v2#3]
## Description
네비게이션의 이동과 회원가입 스크린을 구현합니다.

## Todo
- [ ] 네비게이션 컴포넌트 사용 설정
- [ ] 네비게이션 그래프 생성
- [ ] 회원가입 화면 구성
- [ ] 로그인에서 회원가입으로 넘어갈 수 있도록 연결
- [ ] 회원가입 state 생성
- [ ] 회원가입 뷰모델 생성 및 state 변경 함수 구현

## ETC
로그인과 마찬가지로 에러 처리, 서버와의 연결은 따로 기능으로 빠집니다.
