### ISSUE TITLE
에러 처리

### ISSUE THREAD

**Issue by rootachieve** [JNU-econovation/jnu-wiki-aos-v2#4]
## Description
application 클래스를 만들고 해당 위치에 에러 처리 및 토스트 기능을 만듭니다.
## Todo
- [ ] application class 생성 및 등록
- [ ] 토스트 생성 기능 구현
- [ ] 에러 처리 전략 enum 생성(혹은 sealed)
- [ ] 에러 처리 기능 구현

## ETC
